import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/layouts/Navbar";
import Footer from "@/_components/layouts/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "bookleaf",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Navbar/>
        {children}
        <Footer/>
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: "#FAF7F2",
              color: "#3E2F24",
              border: "1px solid #D8CFC4",
              padding: "14px 18px",
              borderRadius: "14px",
              fontSize: "14px",
            },
            success: {
              iconTheme: {
                primary: "#556B2F",
                secondary: "#FAF7F2",
              },
            },
            error: {
              iconTheme: {
                primary: "#8B3A3A",
                secondary: "#FAF7F2",
              },
            },
          }}
        />

      </body>
    </html>
  );
}
